//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO_CSharp_DesktopApps_FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public long CustomerID { get; set; }
        public int CustomerTitleID { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerOtherInitials { get; set; }
        public string CustomerLastName { get; set; }
        public long AddressID { get; set; }
        public string AccountNumber { get; set; }
        public int AccountTypeID { get; set; }
        public decimal CleareBalance { get; set; }
        public decimal UncleareBalance { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
