//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO_CSharp_DesktopApps_FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersProducts
    {
        public long CustomerFinancialProductID { get; set; }
        public long CustomerId { get; set; }
        public long FinancialProductID { get; set; }
        public decimal AmountToCollect { get; set; }
        public short Frequency { get; set; }
        public System.DateTime LastCollected { get; set; }
        public System.DateTime LastCollection { get; set; }
        public bool Renewable { get; set; }
    }
}
