//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO_CSharp_DesktopApps_FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shares()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public long ShareID { get; set; }
        public string ShareDesc { get; set; }
        public string ShareTickerID { get; set; }
        public decimal CurrentPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
