//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO_CSharp_DesktopApps_FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTypes
    {
        public int TransactionTypesID { get; set; }
        public string TransactionDescription { get; set; }
        public bool CreditType { get; set; }
        public bool AffectCashBalance { get; set; }
    }
}
